# Generated by Django 6.0 on 2026-01-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='News Portal', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Recommended size: 200x50px', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload .ico or .png', null=True, upload_to='site/')),
                ('meta_description', models.TextField(blank=True, help_text='For SEO: Description of the website')),
                ('breaking_news_title', models.CharField(default='BREAKING', max_length=50)),
                ('footer_text', models.CharField(default='© 2026 News Portal. All rights reserved.', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
