# Generated by Django 6.0 on 2026-01-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='breaking_news_content',
            field=models.TextField(default='Welcome to the News Portal! This is a demo of the Breaking News Ticker.', help_text='Text to scroll in the header.'),
        ),
    ]
